CREATE TABLE IF NOT EXISTS users
   (
       user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       user_name varchar(50)  NOT NULL,
       user_email varchar(100)  NOT NULL,
       UNIQUE(user_email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_description varchar(50)  NOT NULL,
    request_requester_id INTEGER REFERENCES USERS (user_id) ON DELETE CASCADE,
    request_create_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_description varchar(500)  NOT NULL,
    item_name varchar(50)  NOT NULL,
    item_is_available boolean,
    item_owner_id INTEGER REFERENCES USERS (user_id) ON DELETE CASCADE,
    item_request_id INTEGER REFERENCES REQUESTS (request_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text varchar(500) NOT NULL,
    comment_author_id INTEGER REFERENCES USERS (user_id) ON DELETE CASCADE,
    comment_item_id INTEGER REFERENCES ITEMS (item_id) ON DELETE CASCADE,
    comment_created TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_start_date TIMESTAMP WITHOUT TIME ZONE,
    booking_end_date TIMESTAMP WITHOUT TIME ZONE,
    booking_item_id INTEGER REFERENCES ITEMS (item_id) ON DELETE CASCADE,
    booking_booker_id INTEGER REFERENCES USERS (user_id) ON DELETE CASCADE,
    booking_status varchar(50)
);
